language: go
sudo: false
dist: trusty
go:
  - 1.x
  - 1.9.x
  - 1.8.x
  - master

env:
  DEP_VER=0.4.1
  CONSUL_VER=1.0.7
  PATH=$HOME/bin:$PATH
  
install:
  - dep ensure

before_install:
  - wget "https://releases.hashicorp.com/consul/${CONSUL_VER}/consul_${CONSUL_VER}_linux_amd64.zip"
  - mkdir -p $HOME/bin
  - unzip -d $HOME/bin consul_${CONSUL_VER}_linux_amd64.zip
  - wget "https://github.com/golang/dep/releases/download/v$DEP_VER/dep-linux-amd64"
  - cp dep-linux-amd64 $HOME/bin/dep
  - chmod 755 $HOME/bin/*

script:
  - go test
  - go install
