language: go
sudo: false
dist: trusty
go:
  - 1.x
  - 1.14.x
  - 1.15.x
  - master

env:
  CONSUL_VER=1.8.5
  PATH=$HOME/bin:$PATH
  GO111MODULE=on
  
install:
  - go mod download

before_install:
  - wget "https://releases.hashicorp.com/consul/${CONSUL_VER}/consul_${CONSUL_VER}_linux_amd64.zip"
  - mkdir -p $HOME/bin
  - unzip -d $HOME/bin consul_${CONSUL_VER}_linux_amd64.zip

script:
  - go test
  - go install
