on: [ push, pull_request ]
name: Build
jobs:
  build:
    env:
      CONSUL_VER: '1.13.1'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go: [ '1.19' ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install consul
        run: |
          wget "https://releases.hashicorp.com/consul/${CONSUL_VER}/consul_${CONSUL_VER}_linux_amd64.zip"
          mkdir -p $HOME/bin
          unzip -d $HOME/bin consul_${CONSUL_VER}_linux_amd64.zip
      - name: Test
        run: |
          export PATH=$HOME/bin:$PATH
          go test
